### ISSUE TITLE
Cannot View Documents or Apps

### ISSUE THREAD

**Issue by engti** [dm3ll3n/ShinyStudio#8]
Hi,

So I am now able to run Rstudio and Code. And from within RStudio pane I can run shiny apps and knit documents.

But when I go to the Apps & Reports or Documents from the main landing page, I only see a "Index of /" message. None of the default apps are available. Even though I can see it from the VS Code file explorer.

I even followed the gif walkthrough for creating the markdown file. But still see nothing.

One thing I have done is created a new site by creating a 80_8080_Site1.yml and am accessing this from port 80 [i.e. by not specifying any port]

This new yml file is an exact copy of 8080_Site1.yml

Any idea of what I am missing out on?

![image](https://user-images.githubusercontent.com/1890066/58649095-deb75c80-8328-11e9-97c8-d2da2912c27c.png)

**Comment by fresh2dev** [comment]
I corrected a bug in the first-time setup that affected superadmins that was present in the base image sooner after the release of the latest version (v2). You may have pulled it just before the fix was implemented.

Please run `./control.sh update` to pull the latest image from DockerHub.

I will update the documentation based on this issue, but so you have a better understanding of the site structure...

The `.yml` files should be named according to `{PORT}_{SITEID}.yml`.

* The "Apps & Reports" pane reads content from `.../sites/{SITEID}/_apps`.
* The "Documents" pane reads from `.../sites/{SITEID}/_apps`.
* The "Personal" pane reads from `.../users/{USERNAME}`.

So, using the default config file `8080_Site1.yml`, apps/docs are read from:

* `.../sites/Site1/_apps`
* `.../sites/Site1/_docs`

You can use VS Code / RStudio to move the sample content around to the proper locations.

I'll leave this issue open, awaiting your reply, just in case you have issues pulling the latest image or have a follow-up question.

Thanks,
Donald

**Comment by fresh2dev** [comment]
Argh, just identified another issue when running as `superadmin`. Stay tuned for a new image. Until then, running as `admin` should work fine.

**Comment by engti** [comment]
Thanks. Logged into admin, and still see no default docs or apps.

I believe that when I created the file 80_8080_Site1.yml  and ran setup, it's somehow not picking out Site1.

When I access _myip:8080_ I can see Site 1 content but when I access _myip_ alone, I can't see Site1 content from Apps or Docs. I can see it from the VS Code explorer though.

Really appreciate you helping out. If you need me to update any documentation in support, I'd be glad to help. I'm deploying this on a GCP server.

**Comment by fresh2dev** [comment]
I appreciate the feedback. You identified another bug, which is that the SITEID in `PORT_SITEID.yml` cannot contain underscores. I corrected and a few other issues related to the first-time launch. I will push later this evening after further evaluation.

For the time being, if you'd like, start from scratch, with the default config, and log in as `admin`. Open either IDE *first*, before accessing apps or docs.

I'll follow up when I push the updates.

**Comment by fresh2dev** [comment]
Okay, I pushed updates to both the base image (on DockerHub) and the master branch (for enhanced setup). Now, any time "Apps & Reports" or "Documents" is empty, the example content will first be copied to it. However, that is only done when either IDE is opened. For example, if you login for the first time and click "Documents", nothing will show. If you then open either IDE, then refresh "Documents", you will see the example content. You can also have underscores in the SITEID if desired.

Please setup from scratch and let me know how it goes.

Thanks,
Donald

**Comment by engti** [comment]
Awesome. Just did it. It's working great.  I can access apps, documents and the port 80 redirect is working just fine.

I guess in a few days I might trouble you for how to setup a Letsencrpt cert. I had done it previously for a regular Shinyproxy install. I imagine it's much the same? But I'm good for now.

Thanks a whole bunch. Really appreciate the time you've put into this.

Cheers :)

**Comment by fresh2dev** [comment]
Glad to hear it!

I've made some good progress in integrating NGINX into the ShinyStudio stack for a SSL-secured site, but not specifically for LetsEncrypt.

The repo below (and its references) provides a good example of using ShinyProxy and NGINX with LetsEncrypt and auto-renewing certs.

https://github.com/TelethonKids/deploy_shiny_app

Hope it helps.
